id: IBC1E620B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T14:47:38+00:00'
last_modified: '2022-06-07T12:22:59.622977+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD87837
  title: མངའ་རིས་མང་ཡུལ་སྐྱིད་གྲོང་རྒྱ་དགུའི་ལོ་རྒྱུས་དང་འབྲེལ་བའི་བློ་བཟང་སྒྲོལ་མའི་ནང་མིའི་ལོ་རྒྱུས་ནོར་བུའི་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    E136:
      image_group_id: I1KG11805
      title: Volume 1 of mnga' ris mang yul skyid grong rgya dgu'i lo rgyus dang 'brel
        ba'i blo bzang sgrol ma'i nang mi'i lo rgyus nor bu'i me long /
      total_pages: 442
      order: 1
      base_file: E136.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
