id: P000583
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-16 15:48:22.867722
source_metadata:
  id: bdr:W1PD87837
  title: མངའ་རིས་མང་ཡུལ་སྐྱིད་གྲོང་རྒྱ་དགུའི་ལོ་རྒྱུས་དང་འབྲེལ་བའི་བློ་བཟང་སྒྲོལ་མའི་ནང་མིའི་ལོ་རྒྱུས་ནོར་བུའི་མེ་ལོང་།
  author: ''
  volumes:
    d98f514041ee4c1585d53334819495ac:
      image_group_id: I1KG11805
      title: Volume 1 of mnga' ris mang yul skyid grong rgya dgu'i lo rgyus dang 'brel
        ba'i blo bzang sgrol ma'i nang mi'i lo rgyus nor bu'i me long /
      volume_number: 1
      total_pages: 442
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
