id: opecha:P000583
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD87837
  title: མངའ་རིས་མང་ཡུལ་སྐྱིད་གྲོང་རྒྱ་དགུའི་ལོ་རྒྱུས་དང་འབྲེལ་བའི་བློ་བཟང་སྒྲོལ་མའི་ནང་མིའི་ལོ་རྒྱུས་ནོར་བུའི་མེ་ལོང་།
  volume: ''
  author: ''
